syntax = "proto3";

package gokeeper;

option go_package = "github.com/Albert-Ti/go-keeper/pkg/proto";

import "google/protobuf/timestamp.proto";

message ArbitraryData {
  int64 id = 1;
  string name = 2;
  string type = 3;
  string object_key = 4;
  google.protobuf.Timestamp created_at = 5;
}

message ListArbitraryDataRequest {}

message ListArbitraryDataResponse {
  repeated ArbitraryData arbitrary_data = 1;
}

message DownloadArbitraryDataRequest {
  int64 id = 1;
}

message DownloadArbitraryDataResponse {
  bytes chunk = 1;
}

message FileMetadata {
  string filename = 1;
  string type = 2;
}

message CreateArbitraryDataRequest {
  oneof data {
    FileMetadata metadata = 1;
    bytes chunk = 2;
  }
}

message CreateArbitraryDataResponse {}

message DeleteArbitraryDataRequest {
  int64 id = 1;
}

message DeleteArbitraryDataResponse {}