// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: arbitrary_data.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArbitraryData struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id        int64                  `protobuf:"varint,1,opt,name=id,proto3"`
	xxx_hidden_Name      string                 `protobuf:"bytes,2,opt,name=name,proto3"`
	xxx_hidden_Type      string                 `protobuf:"bytes,3,opt,name=type,proto3"`
	xxx_hidden_ObjectKey string                 `protobuf:"bytes,4,opt,name=object_key,json=objectKey,proto3"`
	xxx_hidden_CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ArbitraryData) Reset() {
	*x = ArbitraryData{}
	mi := &file_arbitrary_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArbitraryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArbitraryData) ProtoMessage() {}

func (x *ArbitraryData) ProtoReflect() protoreflect.Message {
	mi := &file_arbitrary_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ArbitraryData) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *ArbitraryData) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *ArbitraryData) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *ArbitraryData) GetObjectKey() string {
	if x != nil {
		return x.xxx_hidden_ObjectKey
	}
	return ""
}

func (x *ArbitraryData) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *ArbitraryData) SetId(v int64) {
	x.xxx_hidden_Id = v
}

func (x *ArbitraryData) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *ArbitraryData) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *ArbitraryData) SetObjectKey(v string) {
	x.xxx_hidden_ObjectKey = v
}

func (x *ArbitraryData) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *ArbitraryData) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *ArbitraryData) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

type ArbitraryData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        int64
	Name      string
	Type      string
	ObjectKey string
	CreatedAt *timestamppb.Timestamp
}

func (b0 ArbitraryData_builder) Build() *ArbitraryData {
	m0 := &ArbitraryData{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_ObjectKey = b.ObjectKey
	x.xxx_hidden_CreatedAt = b.CreatedAt
	return m0
}

type ArbitraryDataRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArbitraryDataRequest) Reset() {
	*x = ArbitraryDataRequest{}
	mi := &file_arbitrary_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArbitraryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArbitraryDataRequest) ProtoMessage() {}

func (x *ArbitraryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbitrary_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ArbitraryDataRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ArbitraryDataRequest_builder) Build() *ArbitraryDataRequest {
	m0 := &ArbitraryDataRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ArbitraryDataResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ArbitraryData *[]*ArbitraryData      `protobuf:"bytes,1,rep,name=arbitrary_data,json=arbitraryData,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ArbitraryDataResponse) Reset() {
	*x = ArbitraryDataResponse{}
	mi := &file_arbitrary_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArbitraryDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArbitraryDataResponse) ProtoMessage() {}

func (x *ArbitraryDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbitrary_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ArbitraryDataResponse) GetArbitraryData() []*ArbitraryData {
	if x != nil {
		if x.xxx_hidden_ArbitraryData != nil {
			return *x.xxx_hidden_ArbitraryData
		}
	}
	return nil
}

func (x *ArbitraryDataResponse) SetArbitraryData(v []*ArbitraryData) {
	x.xxx_hidden_ArbitraryData = &v
}

type ArbitraryDataResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ArbitraryData []*ArbitraryData
}

func (b0 ArbitraryDataResponse_builder) Build() *ArbitraryDataResponse {
	m0 := &ArbitraryDataResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ArbitraryData = &b.ArbitraryData
	return m0
}

type CreateArbitraryDataRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filename string                 `protobuf:"bytes,1,opt,name=filename,proto3"`
	xxx_hidden_Payload  []byte                 `protobuf:"bytes,2,opt,name=payload,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateArbitraryDataRequest) Reset() {
	*x = CreateArbitraryDataRequest{}
	mi := &file_arbitrary_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArbitraryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArbitraryDataRequest) ProtoMessage() {}

func (x *CreateArbitraryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbitrary_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateArbitraryDataRequest) GetFilename() string {
	if x != nil {
		return x.xxx_hidden_Filename
	}
	return ""
}

func (x *CreateArbitraryDataRequest) GetPayload() []byte {
	if x != nil {
		return x.xxx_hidden_Payload
	}
	return nil
}

func (x *CreateArbitraryDataRequest) SetFilename(v string) {
	x.xxx_hidden_Filename = v
}

func (x *CreateArbitraryDataRequest) SetPayload(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Payload = v
}

type CreateArbitraryDataRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Filename string
	Payload  []byte
}

func (b0 CreateArbitraryDataRequest_builder) Build() *CreateArbitraryDataRequest {
	m0 := &CreateArbitraryDataRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filename = b.Filename
	x.xxx_hidden_Payload = b.Payload
	return m0
}

type CreateArbitraryDataResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArbitraryDataResponse) Reset() {
	*x = CreateArbitraryDataResponse{}
	mi := &file_arbitrary_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArbitraryDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArbitraryDataResponse) ProtoMessage() {}

func (x *CreateArbitraryDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbitrary_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type CreateArbitraryDataResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 CreateArbitraryDataResponse_builder) Build() *CreateArbitraryDataResponse {
	m0 := &CreateArbitraryDataResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type DeleteArbitraryDataRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id int64                  `protobuf:"varint,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArbitraryDataRequest) Reset() {
	*x = DeleteArbitraryDataRequest{}
	mi := &file_arbitrary_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArbitraryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArbitraryDataRequest) ProtoMessage() {}

func (x *DeleteArbitraryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbitrary_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteArbitraryDataRequest) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *DeleteArbitraryDataRequest) SetId(v int64) {
	x.xxx_hidden_Id = v
}

type DeleteArbitraryDataRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id int64
}

func (b0 DeleteArbitraryDataRequest_builder) Build() *DeleteArbitraryDataRequest {
	m0 := &DeleteArbitraryDataRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type DeleteArbitraryDataResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArbitraryDataResponse) Reset() {
	*x = DeleteArbitraryDataResponse{}
	mi := &file_arbitrary_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArbitraryDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArbitraryDataResponse) ProtoMessage() {}

func (x *DeleteArbitraryDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbitrary_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteArbitraryDataResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteArbitraryDataResponse_builder) Build() *DeleteArbitraryDataResponse {
	m0 := &DeleteArbitraryDataResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_arbitrary_data_proto protoreflect.FileDescriptor

const file_arbitrary_data_proto_rawDesc = "" +
	"\n" +
	"\x14arbitrary_data.proto\x12\bgokeeper\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa1\x01\n" +
	"\rArbitraryData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"object_key\x18\x04 \x01(\tR\tobjectKey\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x16\n" +
	"\x14ArbitraryDataRequest\"W\n" +
	"\x15ArbitraryDataResponse\x12>\n" +
	"\x0earbitrary_data\x18\x01 \x03(\v2\x17.gokeeper.ArbitraryDataR\rarbitraryData\"R\n" +
	"\x1aCreateArbitraryDataRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\x1d\n" +
	"\x1bCreateArbitraryDataResponse\",\n" +
	"\x1aDeleteArbitraryDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1d\n" +
	"\x1bDeleteArbitraryDataResponseB*Z(github.com/Albert-Ti/go-keeper/pkg/protob\x06proto3"

var file_arbitrary_data_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_arbitrary_data_proto_goTypes = []any{
	(*ArbitraryData)(nil),               // 0: gokeeper.ArbitraryData
	(*ArbitraryDataRequest)(nil),        // 1: gokeeper.ArbitraryDataRequest
	(*ArbitraryDataResponse)(nil),       // 2: gokeeper.ArbitraryDataResponse
	(*CreateArbitraryDataRequest)(nil),  // 3: gokeeper.CreateArbitraryDataRequest
	(*CreateArbitraryDataResponse)(nil), // 4: gokeeper.CreateArbitraryDataResponse
	(*DeleteArbitraryDataRequest)(nil),  // 5: gokeeper.DeleteArbitraryDataRequest
	(*DeleteArbitraryDataResponse)(nil), // 6: gokeeper.DeleteArbitraryDataResponse
	(*timestamppb.Timestamp)(nil),       // 7: google.protobuf.Timestamp
}
var file_arbitrary_data_proto_depIdxs = []int32{
	7, // 0: gokeeper.ArbitraryData.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: gokeeper.ArbitraryDataResponse.arbitrary_data:type_name -> gokeeper.ArbitraryData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_arbitrary_data_proto_init() }
func file_arbitrary_data_proto_init() {
	if File_arbitrary_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arbitrary_data_proto_rawDesc), len(file_arbitrary_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_arbitrary_data_proto_goTypes,
		DependencyIndexes: file_arbitrary_data_proto_depIdxs,
		MessageInfos:      file_arbitrary_data_proto_msgTypes,
	}.Build()
	File_arbitrary_data_proto = out.File
	file_arbitrary_data_proto_goTypes = nil
	file_arbitrary_data_proto_depIdxs = nil
}
