// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: arbitrary_data.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArbitraryData struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id         int64                  `protobuf:"varint,1,opt,name=id,proto3"`
	xxx_hidden_Name       string                 `protobuf:"bytes,2,opt,name=name,proto3"`
	xxx_hidden_Type       string                 `protobuf:"bytes,3,opt,name=type,proto3"`
	xxx_hidden_ObjectKey  string                 `protobuf:"bytes,4,opt,name=object_key,json=objectKey,proto3"`
	xxx_hidden_Status     int64                  `protobuf:"varint,5,opt,name=status,proto3"`
	xxx_hidden_ClientSize int64                  `protobuf:"varint,6,opt,name=client_size,json=clientSize,proto3"`
	xxx_hidden_TotalSize  int64                  `protobuf:"varint,7,opt,name=total_size,json=totalSize,proto3"`
	xxx_hidden_CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ArbitraryData) Reset() {
	*x = ArbitraryData{}
	mi := &file_arbitrary_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArbitraryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArbitraryData) ProtoMessage() {}

func (x *ArbitraryData) ProtoReflect() protoreflect.Message {
	mi := &file_arbitrary_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ArbitraryData) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *ArbitraryData) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *ArbitraryData) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *ArbitraryData) GetObjectKey() string {
	if x != nil {
		return x.xxx_hidden_ObjectKey
	}
	return ""
}

func (x *ArbitraryData) GetStatus() int64 {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return 0
}

func (x *ArbitraryData) GetClientSize() int64 {
	if x != nil {
		return x.xxx_hidden_ClientSize
	}
	return 0
}

func (x *ArbitraryData) GetTotalSize() int64 {
	if x != nil {
		return x.xxx_hidden_TotalSize
	}
	return 0
}

func (x *ArbitraryData) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *ArbitraryData) SetId(v int64) {
	x.xxx_hidden_Id = v
}

func (x *ArbitraryData) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *ArbitraryData) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *ArbitraryData) SetObjectKey(v string) {
	x.xxx_hidden_ObjectKey = v
}

func (x *ArbitraryData) SetStatus(v int64) {
	x.xxx_hidden_Status = v
}

func (x *ArbitraryData) SetClientSize(v int64) {
	x.xxx_hidden_ClientSize = v
}

func (x *ArbitraryData) SetTotalSize(v int64) {
	x.xxx_hidden_TotalSize = v
}

func (x *ArbitraryData) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *ArbitraryData) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *ArbitraryData) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

type ArbitraryData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id         int64
	Name       string
	Type       string
	ObjectKey  string
	Status     int64
	ClientSize int64
	TotalSize  int64
	CreatedAt  *timestamppb.Timestamp
}

func (b0 ArbitraryData_builder) Build() *ArbitraryData {
	m0 := &ArbitraryData{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_ObjectKey = b.ObjectKey
	x.xxx_hidden_Status = b.Status
	x.xxx_hidden_ClientSize = b.ClientSize
	x.xxx_hidden_TotalSize = b.TotalSize
	x.xxx_hidden_CreatedAt = b.CreatedAt
	return m0
}

type ListArbitraryDataRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArbitraryDataRequest) Reset() {
	*x = ListArbitraryDataRequest{}
	mi := &file_arbitrary_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArbitraryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArbitraryDataRequest) ProtoMessage() {}

func (x *ListArbitraryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbitrary_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ListArbitraryDataRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ListArbitraryDataRequest_builder) Build() *ListArbitraryDataRequest {
	m0 := &ListArbitraryDataRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListArbitraryDataResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ArbitraryData *[]*ArbitraryData      `protobuf:"bytes,1,rep,name=arbitrary_data,json=arbitraryData,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ListArbitraryDataResponse) Reset() {
	*x = ListArbitraryDataResponse{}
	mi := &file_arbitrary_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArbitraryDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArbitraryDataResponse) ProtoMessage() {}

func (x *ListArbitraryDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbitrary_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListArbitraryDataResponse) GetArbitraryData() []*ArbitraryData {
	if x != nil {
		if x.xxx_hidden_ArbitraryData != nil {
			return *x.xxx_hidden_ArbitraryData
		}
	}
	return nil
}

func (x *ListArbitraryDataResponse) SetArbitraryData(v []*ArbitraryData) {
	x.xxx_hidden_ArbitraryData = &v
}

type ListArbitraryDataResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ArbitraryData []*ArbitraryData
}

func (b0 ListArbitraryDataResponse_builder) Build() *ListArbitraryDataResponse {
	m0 := &ListArbitraryDataResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ArbitraryData = &b.ArbitraryData
	return m0
}

type DownloadArbitraryDataRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id int64                  `protobuf:"varint,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadArbitraryDataRequest) Reset() {
	*x = DownloadArbitraryDataRequest{}
	mi := &file_arbitrary_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadArbitraryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadArbitraryDataRequest) ProtoMessage() {}

func (x *DownloadArbitraryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbitrary_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadArbitraryDataRequest) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *DownloadArbitraryDataRequest) SetId(v int64) {
	x.xxx_hidden_Id = v
}

type DownloadArbitraryDataRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id int64
}

func (b0 DownloadArbitraryDataRequest_builder) Build() *DownloadArbitraryDataRequest {
	m0 := &DownloadArbitraryDataRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type DownloadArbitraryDataResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Chunk []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DownloadArbitraryDataResponse) Reset() {
	*x = DownloadArbitraryDataResponse{}
	mi := &file_arbitrary_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadArbitraryDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadArbitraryDataResponse) ProtoMessage() {}

func (x *DownloadArbitraryDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbitrary_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadArbitraryDataResponse) GetChunk() []byte {
	if x != nil {
		return x.xxx_hidden_Chunk
	}
	return nil
}

func (x *DownloadArbitraryDataResponse) SetChunk(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Chunk = v
}

type DownloadArbitraryDataResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Chunk []byte
}

func (b0 DownloadArbitraryDataResponse_builder) Build() *DownloadArbitraryDataResponse {
	m0 := &DownloadArbitraryDataResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Chunk = b.Chunk
	return m0
}

type FileMetadata struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filename string                 `protobuf:"bytes,1,opt,name=filename,proto3"`
	xxx_hidden_Type     string                 `protobuf:"bytes,2,opt,name=type,proto3"`
	xxx_hidden_Size     int64                  `protobuf:"varint,3,opt,name=size,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_arbitrary_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_arbitrary_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FileMetadata) GetFilename() string {
	if x != nil {
		return x.xxx_hidden_Filename
	}
	return ""
}

func (x *FileMetadata) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *FileMetadata) GetSize() int64 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *FileMetadata) SetFilename(v string) {
	x.xxx_hidden_Filename = v
}

func (x *FileMetadata) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *FileMetadata) SetSize(v int64) {
	x.xxx_hidden_Size = v
}

type FileMetadata_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Filename string
	Type     string
	Size     int64
}

func (b0 FileMetadata_builder) Build() *FileMetadata {
	m0 := &FileMetadata{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filename = b.Filename
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Size = b.Size
	return m0
}

type CreateArbitraryDataRequest struct {
	state           protoimpl.MessageState            `protogen:"opaque.v1"`
	xxx_hidden_Data isCreateArbitraryDataRequest_Data `protobuf_oneof:"data"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateArbitraryDataRequest) Reset() {
	*x = CreateArbitraryDataRequest{}
	mi := &file_arbitrary_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArbitraryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArbitraryDataRequest) ProtoMessage() {}

func (x *CreateArbitraryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbitrary_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateArbitraryDataRequest) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.xxx_hidden_Data.(*createArbitraryDataRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *CreateArbitraryDataRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Data.(*createArbitraryDataRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *CreateArbitraryDataRequest) SetMetadata(v *FileMetadata) {
	if v == nil {
		x.xxx_hidden_Data = nil
		return
	}
	x.xxx_hidden_Data = &createArbitraryDataRequest_Metadata{v}
}

func (x *CreateArbitraryDataRequest) SetChunk(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = &createArbitraryDataRequest_Chunk{v}
}

func (x *CreateArbitraryDataRequest) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *CreateArbitraryDataRequest) HasMetadata() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Data.(*createArbitraryDataRequest_Metadata)
	return ok
}

func (x *CreateArbitraryDataRequest) HasChunk() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Data.(*createArbitraryDataRequest_Chunk)
	return ok
}

func (x *CreateArbitraryDataRequest) ClearData() {
	x.xxx_hidden_Data = nil
}

func (x *CreateArbitraryDataRequest) ClearMetadata() {
	if _, ok := x.xxx_hidden_Data.(*createArbitraryDataRequest_Metadata); ok {
		x.xxx_hidden_Data = nil
	}
}

func (x *CreateArbitraryDataRequest) ClearChunk() {
	if _, ok := x.xxx_hidden_Data.(*createArbitraryDataRequest_Chunk); ok {
		x.xxx_hidden_Data = nil
	}
}

const CreateArbitraryDataRequest_Data_not_set_case case_CreateArbitraryDataRequest_Data = 0
const CreateArbitraryDataRequest_Metadata_case case_CreateArbitraryDataRequest_Data = 1
const CreateArbitraryDataRequest_Chunk_case case_CreateArbitraryDataRequest_Data = 2

func (x *CreateArbitraryDataRequest) WhichData() case_CreateArbitraryDataRequest_Data {
	if x == nil {
		return CreateArbitraryDataRequest_Data_not_set_case
	}
	switch x.xxx_hidden_Data.(type) {
	case *createArbitraryDataRequest_Metadata:
		return CreateArbitraryDataRequest_Metadata_case
	case *createArbitraryDataRequest_Chunk:
		return CreateArbitraryDataRequest_Chunk_case
	default:
		return CreateArbitraryDataRequest_Data_not_set_case
	}
}

type CreateArbitraryDataRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Data:
	Metadata *FileMetadata
	Chunk    []byte
	// -- end of xxx_hidden_Data
}

func (b0 CreateArbitraryDataRequest_builder) Build() *CreateArbitraryDataRequest {
	m0 := &CreateArbitraryDataRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Metadata != nil {
		x.xxx_hidden_Data = &createArbitraryDataRequest_Metadata{b.Metadata}
	}
	if b.Chunk != nil {
		x.xxx_hidden_Data = &createArbitraryDataRequest_Chunk{b.Chunk}
	}
	return m0
}

type case_CreateArbitraryDataRequest_Data protoreflect.FieldNumber

func (x case_CreateArbitraryDataRequest_Data) String() string {
	md := file_arbitrary_data_proto_msgTypes[6].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isCreateArbitraryDataRequest_Data interface {
	isCreateArbitraryDataRequest_Data()
}

type createArbitraryDataRequest_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type createArbitraryDataRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*createArbitraryDataRequest_Metadata) isCreateArbitraryDataRequest_Data() {}

func (*createArbitraryDataRequest_Chunk) isCreateArbitraryDataRequest_Data() {}

type CreateArbitraryDataResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id int64                  `protobuf:"varint,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArbitraryDataResponse) Reset() {
	*x = CreateArbitraryDataResponse{}
	mi := &file_arbitrary_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArbitraryDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArbitraryDataResponse) ProtoMessage() {}

func (x *CreateArbitraryDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbitrary_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateArbitraryDataResponse) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *CreateArbitraryDataResponse) SetId(v int64) {
	x.xxx_hidden_Id = v
}

type CreateArbitraryDataResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id int64
}

func (b0 CreateArbitraryDataResponse_builder) Build() *CreateArbitraryDataResponse {
	m0 := &CreateArbitraryDataResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type DeleteArbitraryDataRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id int64                  `protobuf:"varint,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArbitraryDataRequest) Reset() {
	*x = DeleteArbitraryDataRequest{}
	mi := &file_arbitrary_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArbitraryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArbitraryDataRequest) ProtoMessage() {}

func (x *DeleteArbitraryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbitrary_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteArbitraryDataRequest) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *DeleteArbitraryDataRequest) SetId(v int64) {
	x.xxx_hidden_Id = v
}

type DeleteArbitraryDataRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id int64
}

func (b0 DeleteArbitraryDataRequest_builder) Build() *DeleteArbitraryDataRequest {
	m0 := &DeleteArbitraryDataRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type DeleteArbitraryDataResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArbitraryDataResponse) Reset() {
	*x = DeleteArbitraryDataResponse{}
	mi := &file_arbitrary_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArbitraryDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArbitraryDataResponse) ProtoMessage() {}

func (x *DeleteArbitraryDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbitrary_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteArbitraryDataResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteArbitraryDataResponse_builder) Build() *DeleteArbitraryDataResponse {
	m0 := &DeleteArbitraryDataResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ReloadArbitraryDataRequest struct {
	state           protoimpl.MessageState            `protogen:"opaque.v1"`
	xxx_hidden_Data isReloadArbitraryDataRequest_Data `protobuf_oneof:"data"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReloadArbitraryDataRequest) Reset() {
	*x = ReloadArbitraryDataRequest{}
	mi := &file_arbitrary_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadArbitraryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadArbitraryDataRequest) ProtoMessage() {}

func (x *ReloadArbitraryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbitrary_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReloadArbitraryDataRequest) GetId() int64 {
	if x != nil {
		if x, ok := x.xxx_hidden_Data.(*reloadArbitraryDataRequest_Id); ok {
			return x.Id
		}
	}
	return 0
}

func (x *ReloadArbitraryDataRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Data.(*reloadArbitraryDataRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *ReloadArbitraryDataRequest) SetId(v int64) {
	x.xxx_hidden_Data = &reloadArbitraryDataRequest_Id{v}
}

func (x *ReloadArbitraryDataRequest) SetChunk(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = &reloadArbitraryDataRequest_Chunk{v}
}

func (x *ReloadArbitraryDataRequest) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *ReloadArbitraryDataRequest) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Data.(*reloadArbitraryDataRequest_Id)
	return ok
}

func (x *ReloadArbitraryDataRequest) HasChunk() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Data.(*reloadArbitraryDataRequest_Chunk)
	return ok
}

func (x *ReloadArbitraryDataRequest) ClearData() {
	x.xxx_hidden_Data = nil
}

func (x *ReloadArbitraryDataRequest) ClearId() {
	if _, ok := x.xxx_hidden_Data.(*reloadArbitraryDataRequest_Id); ok {
		x.xxx_hidden_Data = nil
	}
}

func (x *ReloadArbitraryDataRequest) ClearChunk() {
	if _, ok := x.xxx_hidden_Data.(*reloadArbitraryDataRequest_Chunk); ok {
		x.xxx_hidden_Data = nil
	}
}

const ReloadArbitraryDataRequest_Data_not_set_case case_ReloadArbitraryDataRequest_Data = 0
const ReloadArbitraryDataRequest_Id_case case_ReloadArbitraryDataRequest_Data = 1
const ReloadArbitraryDataRequest_Chunk_case case_ReloadArbitraryDataRequest_Data = 2

func (x *ReloadArbitraryDataRequest) WhichData() case_ReloadArbitraryDataRequest_Data {
	if x == nil {
		return ReloadArbitraryDataRequest_Data_not_set_case
	}
	switch x.xxx_hidden_Data.(type) {
	case *reloadArbitraryDataRequest_Id:
		return ReloadArbitraryDataRequest_Id_case
	case *reloadArbitraryDataRequest_Chunk:
		return ReloadArbitraryDataRequest_Chunk_case
	default:
		return ReloadArbitraryDataRequest_Data_not_set_case
	}
}

type ReloadArbitraryDataRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Data:
	Id    *int64
	Chunk []byte
	// -- end of xxx_hidden_Data
}

func (b0 ReloadArbitraryDataRequest_builder) Build() *ReloadArbitraryDataRequest {
	m0 := &ReloadArbitraryDataRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Data = &reloadArbitraryDataRequest_Id{*b.Id}
	}
	if b.Chunk != nil {
		x.xxx_hidden_Data = &reloadArbitraryDataRequest_Chunk{b.Chunk}
	}
	return m0
}

type case_ReloadArbitraryDataRequest_Data protoreflect.FieldNumber

func (x case_ReloadArbitraryDataRequest_Data) String() string {
	md := file_arbitrary_data_proto_msgTypes[10].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isReloadArbitraryDataRequest_Data interface {
	isReloadArbitraryDataRequest_Data()
}

type reloadArbitraryDataRequest_Id struct {
	Id int64 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type reloadArbitraryDataRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*reloadArbitraryDataRequest_Id) isReloadArbitraryDataRequest_Data() {}

func (*reloadArbitraryDataRequest_Chunk) isReloadArbitraryDataRequest_Data() {}

type ReloadArbitraryDataResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadArbitraryDataResponse) Reset() {
	*x = ReloadArbitraryDataResponse{}
	mi := &file_arbitrary_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadArbitraryDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadArbitraryDataResponse) ProtoMessage() {}

func (x *ReloadArbitraryDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbitrary_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ReloadArbitraryDataResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ReloadArbitraryDataResponse_builder) Build() *ReloadArbitraryDataResponse {
	m0 := &ReloadArbitraryDataResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_arbitrary_data_proto protoreflect.FileDescriptor

const file_arbitrary_data_proto_rawDesc = "" +
	"\n" +
	"\x14arbitrary_data.proto\x12\bgokeeper\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x01\n" +
	"\rArbitraryData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"object_key\x18\x04 \x01(\tR\tobjectKey\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x03R\x06status\x12\x1f\n" +
	"\vclient_size\x18\x06 \x01(\x03R\n" +
	"clientSize\x12\x1d\n" +
	"\n" +
	"total_size\x18\a \x01(\x03R\ttotalSize\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x1a\n" +
	"\x18ListArbitraryDataRequest\"[\n" +
	"\x19ListArbitraryDataResponse\x12>\n" +
	"\x0earbitrary_data\x18\x01 \x03(\v2\x17.gokeeper.ArbitraryDataR\rarbitraryData\".\n" +
	"\x1cDownloadArbitraryDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"5\n" +
	"\x1dDownloadArbitraryDataResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"R\n" +
	"\fFileMetadata\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"r\n" +
	"\x1aCreateArbitraryDataRequest\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.gokeeper.FileMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"-\n" +
	"\x1bCreateArbitraryDataResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\",\n" +
	"\x1aDeleteArbitraryDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1d\n" +
	"\x1bDeleteArbitraryDataResponse\"N\n" +
	"\x1aReloadArbitraryDataRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"\x1d\n" +
	"\x1bReloadArbitraryDataResponseB*Z(github.com/Albert-Ti/go-keeper/pkg/protob\x06proto3"

var file_arbitrary_data_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_arbitrary_data_proto_goTypes = []any{
	(*ArbitraryData)(nil),                 // 0: gokeeper.ArbitraryData
	(*ListArbitraryDataRequest)(nil),      // 1: gokeeper.ListArbitraryDataRequest
	(*ListArbitraryDataResponse)(nil),     // 2: gokeeper.ListArbitraryDataResponse
	(*DownloadArbitraryDataRequest)(nil),  // 3: gokeeper.DownloadArbitraryDataRequest
	(*DownloadArbitraryDataResponse)(nil), // 4: gokeeper.DownloadArbitraryDataResponse
	(*FileMetadata)(nil),                  // 5: gokeeper.FileMetadata
	(*CreateArbitraryDataRequest)(nil),    // 6: gokeeper.CreateArbitraryDataRequest
	(*CreateArbitraryDataResponse)(nil),   // 7: gokeeper.CreateArbitraryDataResponse
	(*DeleteArbitraryDataRequest)(nil),    // 8: gokeeper.DeleteArbitraryDataRequest
	(*DeleteArbitraryDataResponse)(nil),   // 9: gokeeper.DeleteArbitraryDataResponse
	(*ReloadArbitraryDataRequest)(nil),    // 10: gokeeper.ReloadArbitraryDataRequest
	(*ReloadArbitraryDataResponse)(nil),   // 11: gokeeper.ReloadArbitraryDataResponse
	(*timestamppb.Timestamp)(nil),         // 12: google.protobuf.Timestamp
}
var file_arbitrary_data_proto_depIdxs = []int32{
	12, // 0: gokeeper.ArbitraryData.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: gokeeper.ListArbitraryDataResponse.arbitrary_data:type_name -> gokeeper.ArbitraryData
	5,  // 2: gokeeper.CreateArbitraryDataRequest.metadata:type_name -> gokeeper.FileMetadata
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_arbitrary_data_proto_init() }
func file_arbitrary_data_proto_init() {
	if File_arbitrary_data_proto != nil {
		return
	}
	file_arbitrary_data_proto_msgTypes[6].OneofWrappers = []any{
		(*createArbitraryDataRequest_Metadata)(nil),
		(*createArbitraryDataRequest_Chunk)(nil),
	}
	file_arbitrary_data_proto_msgTypes[10].OneofWrappers = []any{
		(*reloadArbitraryDataRequest_Id)(nil),
		(*reloadArbitraryDataRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arbitrary_data_proto_rawDesc), len(file_arbitrary_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_arbitrary_data_proto_goTypes,
		DependencyIndexes: file_arbitrary_data_proto_depIdxs,
		MessageInfos:      file_arbitrary_data_proto_msgTypes,
	}.Build()
	File_arbitrary_data_proto = out.File
	file_arbitrary_data_proto_goTypes = nil
	file_arbitrary_data_proto_depIdxs = nil
}
