syntax = "proto3";

package gokeeper;

option go_package = "github.com/Albert-Ti/go-keeper/pkg/proto";

message RegisterRequest {
  string email  = 1;
  string pass = 2;
}

message  RegisterResponse {}

message LoginRequest {
  string email  = 1;
  string pass = 2;
}

message  LoginResponse {
  string access_token = 1;
  string refresh_token = 2;
}

message TokenRequest {
  string refresh_token = 1;
}

message TokenResponse {
  string access_token = 1;
  string refresh_token = 2;
}

message ConfirmEmailRequest {
  string email = 1;
  string email_code = 2;
}

message ConfirmEmailResponse {}
