// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: base.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_base_proto protoreflect.FileDescriptor

const file_base_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"base.proto\x12\bgokeeper\x1a\n" +
	"auth.proto\x1a\n" +
	"user.proto\x1a\n" +
	"card.proto\x1a\x14arbitrary_data.proto2\xcb\b\n" +
	"\x0fGoKeeperService\x12A\n" +
	"\bRegister\x12\x19.gokeeper.RegisterRequest\x1a\x1a.gokeeper.RegisterResponse\x128\n" +
	"\x05Login\x12\x16.gokeeper.LoginRequest\x1a\x17.gokeeper.LoginResponse\x12M\n" +
	"\fConfirmEmail\x12\x1d.gokeeper.ConfirmEmailRequest\x1a\x1e.gokeeper.ConfirmEmailResponse\x12?\n" +
	"\fRefreshToken\x12\x16.gokeeper.TokenRequest\x1a\x17.gokeeper.TokenResponse\x12A\n" +
	"\n" +
	"GetProfile\x12\x18.gokeeper.ProfileRequest\x1a\x19.gokeeper.ProfileResponse\x12;\n" +
	"\n" +
	"ChangePass\x12\x15.gokeeper.PassRequest\x1a\x16.gokeeper.PassResponse\x12;\n" +
	"\bGetCards\x12\x16.gokeeper.CardsRequest\x1a\x17.gokeeper.CardsResponse\x12G\n" +
	"\n" +
	"CreateCard\x12\x1b.gokeeper.CreateCardRequest\x1a\x1c.gokeeper.CreateCardResponse\x12G\n" +
	"\n" +
	"DeleteCard\x12\x1b.gokeeper.DeleteCardRequest\x1a\x1c.gokeeper.DeleteCardResponse\x12I\n" +
	"\fActivateCard\x12\x1b.gokeeper.ActiveCardRequest\x1a\x1c.gokeeper.ActiveCardResponse\x12[\n" +
	"\x10GetArbitraryData\x12\".gokeeper.ListArbitraryDataRequest\x1a#.gokeeper.ListArbitraryDataResponse\x12j\n" +
	"\x15DownloadArbitraryData\x12&.gokeeper.DownloadArbitraryDataRequest\x1a'.gokeeper.DownloadArbitraryDataResponse0\x01\x12d\n" +
	"\x13CreateArbitraryData\x12$.gokeeper.CreateArbitraryDataRequest\x1a%.gokeeper.CreateArbitraryDataResponse(\x01\x12b\n" +
	"\x13DeleteArbitraryData\x12$.gokeeper.DeleteArbitraryDataRequest\x1a%.gokeeper.DeleteArbitraryDataResponseB*Z(github.com/Albert-Ti/go-keeper/pkg/protob\x06proto3"

var file_base_proto_goTypes = []any{
	(*RegisterRequest)(nil),               // 0: gokeeper.RegisterRequest
	(*LoginRequest)(nil),                  // 1: gokeeper.LoginRequest
	(*ConfirmEmailRequest)(nil),           // 2: gokeeper.ConfirmEmailRequest
	(*TokenRequest)(nil),                  // 3: gokeeper.TokenRequest
	(*ProfileRequest)(nil),                // 4: gokeeper.ProfileRequest
	(*PassRequest)(nil),                   // 5: gokeeper.PassRequest
	(*CardsRequest)(nil),                  // 6: gokeeper.CardsRequest
	(*CreateCardRequest)(nil),             // 7: gokeeper.CreateCardRequest
	(*DeleteCardRequest)(nil),             // 8: gokeeper.DeleteCardRequest
	(*ActiveCardRequest)(nil),             // 9: gokeeper.ActiveCardRequest
	(*ListArbitraryDataRequest)(nil),      // 10: gokeeper.ListArbitraryDataRequest
	(*DownloadArbitraryDataRequest)(nil),  // 11: gokeeper.DownloadArbitraryDataRequest
	(*CreateArbitraryDataRequest)(nil),    // 12: gokeeper.CreateArbitraryDataRequest
	(*DeleteArbitraryDataRequest)(nil),    // 13: gokeeper.DeleteArbitraryDataRequest
	(*RegisterResponse)(nil),              // 14: gokeeper.RegisterResponse
	(*LoginResponse)(nil),                 // 15: gokeeper.LoginResponse
	(*ConfirmEmailResponse)(nil),          // 16: gokeeper.ConfirmEmailResponse
	(*TokenResponse)(nil),                 // 17: gokeeper.TokenResponse
	(*ProfileResponse)(nil),               // 18: gokeeper.ProfileResponse
	(*PassResponse)(nil),                  // 19: gokeeper.PassResponse
	(*CardsResponse)(nil),                 // 20: gokeeper.CardsResponse
	(*CreateCardResponse)(nil),            // 21: gokeeper.CreateCardResponse
	(*DeleteCardResponse)(nil),            // 22: gokeeper.DeleteCardResponse
	(*ActiveCardResponse)(nil),            // 23: gokeeper.ActiveCardResponse
	(*ListArbitraryDataResponse)(nil),     // 24: gokeeper.ListArbitraryDataResponse
	(*DownloadArbitraryDataResponse)(nil), // 25: gokeeper.DownloadArbitraryDataResponse
	(*CreateArbitraryDataResponse)(nil),   // 26: gokeeper.CreateArbitraryDataResponse
	(*DeleteArbitraryDataResponse)(nil),   // 27: gokeeper.DeleteArbitraryDataResponse
}
var file_base_proto_depIdxs = []int32{
	0,  // 0: gokeeper.GoKeeperService.Register:input_type -> gokeeper.RegisterRequest
	1,  // 1: gokeeper.GoKeeperService.Login:input_type -> gokeeper.LoginRequest
	2,  // 2: gokeeper.GoKeeperService.ConfirmEmail:input_type -> gokeeper.ConfirmEmailRequest
	3,  // 3: gokeeper.GoKeeperService.RefreshToken:input_type -> gokeeper.TokenRequest
	4,  // 4: gokeeper.GoKeeperService.GetProfile:input_type -> gokeeper.ProfileRequest
	5,  // 5: gokeeper.GoKeeperService.ChangePass:input_type -> gokeeper.PassRequest
	6,  // 6: gokeeper.GoKeeperService.GetCards:input_type -> gokeeper.CardsRequest
	7,  // 7: gokeeper.GoKeeperService.CreateCard:input_type -> gokeeper.CreateCardRequest
	8,  // 8: gokeeper.GoKeeperService.DeleteCard:input_type -> gokeeper.DeleteCardRequest
	9,  // 9: gokeeper.GoKeeperService.ActivateCard:input_type -> gokeeper.ActiveCardRequest
	10, // 10: gokeeper.GoKeeperService.GetArbitraryData:input_type -> gokeeper.ListArbitraryDataRequest
	11, // 11: gokeeper.GoKeeperService.DownloadArbitraryData:input_type -> gokeeper.DownloadArbitraryDataRequest
	12, // 12: gokeeper.GoKeeperService.CreateArbitraryData:input_type -> gokeeper.CreateArbitraryDataRequest
	13, // 13: gokeeper.GoKeeperService.DeleteArbitraryData:input_type -> gokeeper.DeleteArbitraryDataRequest
	14, // 14: gokeeper.GoKeeperService.Register:output_type -> gokeeper.RegisterResponse
	15, // 15: gokeeper.GoKeeperService.Login:output_type -> gokeeper.LoginResponse
	16, // 16: gokeeper.GoKeeperService.ConfirmEmail:output_type -> gokeeper.ConfirmEmailResponse
	17, // 17: gokeeper.GoKeeperService.RefreshToken:output_type -> gokeeper.TokenResponse
	18, // 18: gokeeper.GoKeeperService.GetProfile:output_type -> gokeeper.ProfileResponse
	19, // 19: gokeeper.GoKeeperService.ChangePass:output_type -> gokeeper.PassResponse
	20, // 20: gokeeper.GoKeeperService.GetCards:output_type -> gokeeper.CardsResponse
	21, // 21: gokeeper.GoKeeperService.CreateCard:output_type -> gokeeper.CreateCardResponse
	22, // 22: gokeeper.GoKeeperService.DeleteCard:output_type -> gokeeper.DeleteCardResponse
	23, // 23: gokeeper.GoKeeperService.ActivateCard:output_type -> gokeeper.ActiveCardResponse
	24, // 24: gokeeper.GoKeeperService.GetArbitraryData:output_type -> gokeeper.ListArbitraryDataResponse
	25, // 25: gokeeper.GoKeeperService.DownloadArbitraryData:output_type -> gokeeper.DownloadArbitraryDataResponse
	26, // 26: gokeeper.GoKeeperService.CreateArbitraryData:output_type -> gokeeper.CreateArbitraryDataResponse
	27, // 27: gokeeper.GoKeeperService.DeleteArbitraryData:output_type -> gokeeper.DeleteArbitraryDataResponse
	14, // [14:28] is the sub-list for method output_type
	0,  // [0:14] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_base_proto_init() }
func file_base_proto_init() {
	if File_base_proto != nil {
		return
	}
	file_auth_proto_init()
	file_user_proto_init()
	file_card_proto_init()
	file_arbitrary_data_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_proto_rawDesc), len(file_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_base_proto_goTypes,
		DependencyIndexes: file_base_proto_depIdxs,
	}.Build()
	File_base_proto = out.File
	file_base_proto_goTypes = nil
	file_base_proto_depIdxs = nil
}
