// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: base.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_base_proto protoreflect.FileDescriptor

const file_base_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"base.proto\x12\bgokeeper\x1a\n" +
	"auth.proto\x1a\n" +
	"user.proto\x1a\n" +
	"card.proto2\xa4\x04\n" +
	"\x0fGoKeeperService\x12A\n" +
	"\bRegister\x12\x19.gokeeper.RegisterRequest\x1a\x1a.gokeeper.RegisterResponse\x128\n" +
	"\x05Login\x12\x16.gokeeper.LoginRequest\x1a\x17.gokeeper.LoginResponse\x12M\n" +
	"\fConfirmEmail\x12\x1d.gokeeper.ConfirmEmailRequest\x1a\x1e.gokeeper.ConfirmEmailResponse\x12?\n" +
	"\fRefreshToken\x12\x16.gokeeper.TokenRequest\x1a\x17.gokeeper.TokenResponse\x12A\n" +
	"\n" +
	"GetProfile\x12\x18.gokeeper.ProfileRequest\x1a\x19.gokeeper.ProfileResponse\x12;\n" +
	"\n" +
	"ChangePass\x12\x15.gokeeper.PassRequest\x1a\x16.gokeeper.PassResponse\x12;\n" +
	"\bGetCards\x12\x16.gokeeper.CardsRequest\x1a\x17.gokeeper.CardsResponse\x12G\n" +
	"\n" +
	"CreateCard\x12\x1b.gokeeper.CreateCardRequest\x1a\x1c.gokeeper.CreateCardResponseB*Z(github.com/Albert-Ti/go-keeper/pkg/protob\x06proto3"

var file_base_proto_goTypes = []any{
	(*RegisterRequest)(nil),      // 0: gokeeper.RegisterRequest
	(*LoginRequest)(nil),         // 1: gokeeper.LoginRequest
	(*ConfirmEmailRequest)(nil),  // 2: gokeeper.ConfirmEmailRequest
	(*TokenRequest)(nil),         // 3: gokeeper.TokenRequest
	(*ProfileRequest)(nil),       // 4: gokeeper.ProfileRequest
	(*PassRequest)(nil),          // 5: gokeeper.PassRequest
	(*CardsRequest)(nil),         // 6: gokeeper.CardsRequest
	(*CreateCardRequest)(nil),    // 7: gokeeper.CreateCardRequest
	(*RegisterResponse)(nil),     // 8: gokeeper.RegisterResponse
	(*LoginResponse)(nil),        // 9: gokeeper.LoginResponse
	(*ConfirmEmailResponse)(nil), // 10: gokeeper.ConfirmEmailResponse
	(*TokenResponse)(nil),        // 11: gokeeper.TokenResponse
	(*ProfileResponse)(nil),      // 12: gokeeper.ProfileResponse
	(*PassResponse)(nil),         // 13: gokeeper.PassResponse
	(*CardsResponse)(nil),        // 14: gokeeper.CardsResponse
	(*CreateCardResponse)(nil),   // 15: gokeeper.CreateCardResponse
}
var file_base_proto_depIdxs = []int32{
	0,  // 0: gokeeper.GoKeeperService.Register:input_type -> gokeeper.RegisterRequest
	1,  // 1: gokeeper.GoKeeperService.Login:input_type -> gokeeper.LoginRequest
	2,  // 2: gokeeper.GoKeeperService.ConfirmEmail:input_type -> gokeeper.ConfirmEmailRequest
	3,  // 3: gokeeper.GoKeeperService.RefreshToken:input_type -> gokeeper.TokenRequest
	4,  // 4: gokeeper.GoKeeperService.GetProfile:input_type -> gokeeper.ProfileRequest
	5,  // 5: gokeeper.GoKeeperService.ChangePass:input_type -> gokeeper.PassRequest
	6,  // 6: gokeeper.GoKeeperService.GetCards:input_type -> gokeeper.CardsRequest
	7,  // 7: gokeeper.GoKeeperService.CreateCard:input_type -> gokeeper.CreateCardRequest
	8,  // 8: gokeeper.GoKeeperService.Register:output_type -> gokeeper.RegisterResponse
	9,  // 9: gokeeper.GoKeeperService.Login:output_type -> gokeeper.LoginResponse
	10, // 10: gokeeper.GoKeeperService.ConfirmEmail:output_type -> gokeeper.ConfirmEmailResponse
	11, // 11: gokeeper.GoKeeperService.RefreshToken:output_type -> gokeeper.TokenResponse
	12, // 12: gokeeper.GoKeeperService.GetProfile:output_type -> gokeeper.ProfileResponse
	13, // 13: gokeeper.GoKeeperService.ChangePass:output_type -> gokeeper.PassResponse
	14, // 14: gokeeper.GoKeeperService.GetCards:output_type -> gokeeper.CardsResponse
	15, // 15: gokeeper.GoKeeperService.CreateCard:output_type -> gokeeper.CreateCardResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_base_proto_init() }
func file_base_proto_init() {
	if File_base_proto != nil {
		return
	}
	file_auth_proto_init()
	file_user_proto_init()
	file_card_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_proto_rawDesc), len(file_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_base_proto_goTypes,
		DependencyIndexes: file_base_proto_depIdxs,
	}.Build()
	File_base_proto = out.File
	file_base_proto_goTypes = nil
	file_base_proto_depIdxs = nil
}
