// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: card.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardsRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardsRequest) Reset() {
	*x = CardsRequest{}
	mi := &file_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardsRequest) ProtoMessage() {}

func (x *CardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type CardsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 CardsRequest_builder) Build() *CardsRequest {
	m0 := &CardsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type CardData struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CardNumber string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3"`
	xxx_hidden_Active     bool                   `protobuf:"varint,2,opt,name=active,proto3"`
	xxx_hidden_ExpiryDate *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expiry_date,json=expiryDate,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CardData) Reset() {
	*x = CardData{}
	mi := &file_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardData) ProtoMessage() {}

func (x *CardData) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CardData) GetCardNumber() string {
	if x != nil {
		return x.xxx_hidden_CardNumber
	}
	return ""
}

func (x *CardData) GetActive() bool {
	if x != nil {
		return x.xxx_hidden_Active
	}
	return false
}

func (x *CardData) GetExpiryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ExpiryDate
	}
	return nil
}

func (x *CardData) SetCardNumber(v string) {
	x.xxx_hidden_CardNumber = v
}

func (x *CardData) SetActive(v bool) {
	x.xxx_hidden_Active = v
}

func (x *CardData) SetExpiryDate(v *timestamppb.Timestamp) {
	x.xxx_hidden_ExpiryDate = v
}

func (x *CardData) HasExpiryDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiryDate != nil
}

func (x *CardData) ClearExpiryDate() {
	x.xxx_hidden_ExpiryDate = nil
}

type CardData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CardNumber string
	Active     bool
	ExpiryDate *timestamppb.Timestamp
}

func (b0 CardData_builder) Build() *CardData {
	m0 := &CardData{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_CardNumber = b.CardNumber
	x.xxx_hidden_Active = b.Active
	x.xxx_hidden_ExpiryDate = b.ExpiryDate
	return m0
}

type CardsResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cards *[]*CardData           `protobuf:"bytes,1,rep,name=cards,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CardsResponse) Reset() {
	*x = CardsResponse{}
	mi := &file_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardsResponse) ProtoMessage() {}

func (x *CardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CardsResponse) GetCards() []*CardData {
	if x != nil {
		if x.xxx_hidden_Cards != nil {
			return *x.xxx_hidden_Cards
		}
	}
	return nil
}

func (x *CardsResponse) SetCards(v []*CardData) {
	x.xxx_hidden_Cards = &v
}

type CardsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Cards []*CardData
}

func (b0 CardsResponse_builder) Build() *CardsResponse {
	m0 := &CardsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Cards = &b.Cards
	return m0
}

type CreateCardRequest struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CardNumber string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3"`
	xxx_hidden_ExpiryDate string                 `protobuf:"bytes,2,opt,name=expiry_date,json=expiryDate,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateCardRequest) Reset() {
	*x = CreateCardRequest{}
	mi := &file_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardRequest) ProtoMessage() {}

func (x *CreateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateCardRequest) GetCardNumber() string {
	if x != nil {
		return x.xxx_hidden_CardNumber
	}
	return ""
}

func (x *CreateCardRequest) GetExpiryDate() string {
	if x != nil {
		return x.xxx_hidden_ExpiryDate
	}
	return ""
}

func (x *CreateCardRequest) SetCardNumber(v string) {
	x.xxx_hidden_CardNumber = v
}

func (x *CreateCardRequest) SetExpiryDate(v string) {
	x.xxx_hidden_ExpiryDate = v
}

type CreateCardRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CardNumber string
	ExpiryDate string
}

func (b0 CreateCardRequest_builder) Build() *CreateCardRequest {
	m0 := &CreateCardRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_CardNumber = b.CardNumber
	x.xxx_hidden_ExpiryDate = b.ExpiryDate
	return m0
}

type CreateCardResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardResponse) Reset() {
	*x = CreateCardResponse{}
	mi := &file_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardResponse) ProtoMessage() {}

func (x *CreateCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type CreateCardResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 CreateCardResponse_builder) Build() *CreateCardResponse {
	m0 := &CreateCardResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_card_proto protoreflect.FileDescriptor

const file_card_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"card.proto\x12\bgokeeper\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0e\n" +
	"\fCardsRequest\"\x80\x01\n" +
	"\bCardData\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12;\n" +
	"\vexpiry_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiryDate\"9\n" +
	"\rCardsResponse\x12(\n" +
	"\x05cards\x18\x01 \x03(\v2\x12.gokeeper.CardDataR\x05cards\"U\n" +
	"\x11CreateCardRequest\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12\x1f\n" +
	"\vexpiry_date\x18\x02 \x01(\tR\n" +
	"expiryDate\"\x14\n" +
	"\x12CreateCardResponseB*Z(github.com/Albert-Ti/go-keeper/pkg/protob\x06proto3"

var file_card_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_card_proto_goTypes = []any{
	(*CardsRequest)(nil),          // 0: gokeeper.CardsRequest
	(*CardData)(nil),              // 1: gokeeper.CardData
	(*CardsResponse)(nil),         // 2: gokeeper.CardsResponse
	(*CreateCardRequest)(nil),     // 3: gokeeper.CreateCardRequest
	(*CreateCardResponse)(nil),    // 4: gokeeper.CreateCardResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_card_proto_depIdxs = []int32{
	5, // 0: gokeeper.CardData.expiry_date:type_name -> google.protobuf.Timestamp
	1, // 1: gokeeper.CardsResponse.cards:type_name -> gokeeper.CardData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_card_proto_init() }
func file_card_proto_init() {
	if File_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_card_proto_rawDesc), len(file_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_card_proto_goTypes,
		DependencyIndexes: file_card_proto_depIdxs,
		MessageInfos:      file_card_proto_msgTypes,
	}.Build()
	File_card_proto = out.File
	file_card_proto_goTypes = nil
	file_card_proto_depIdxs = nil
}
