// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProfileRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileRequest) Reset() {
	*x = ProfileRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileRequest) ProtoMessage() {}

func (x *ProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ProfileRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ProfileRequest_builder) Build() *ProfileRequest {
	m0 := &ProfileRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ProfileResponse struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Email     string                 `protobuf:"bytes,1,opt,name=email,proto3"`
	xxx_hidden_Password  string                 `protobuf:"bytes,2,opt,name=password,proto3"`
	xxx_hidden_CreatedAt string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfileResponse) GetEmail() string {
	if x != nil {
		return x.xxx_hidden_Email
	}
	return ""
}

func (x *ProfileResponse) GetPassword() string {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return ""
}

func (x *ProfileResponse) GetCreatedAt() string {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return ""
}

func (x *ProfileResponse) SetEmail(v string) {
	x.xxx_hidden_Email = v
}

func (x *ProfileResponse) SetPassword(v string) {
	x.xxx_hidden_Password = v
}

func (x *ProfileResponse) SetCreatedAt(v string) {
	x.xxx_hidden_CreatedAt = v
}

type ProfileResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Email     string
	Password  string
	CreatedAt string
}

func (b0 ProfileResponse_builder) Build() *ProfileResponse {
	m0 := &ProfileResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Email = b.Email
	x.xxx_hidden_Password = b.Password
	x.xxx_hidden_CreatedAt = b.CreatedAt
	return m0
}

type PasswordRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordRequest) Reset() {
	*x = PasswordRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordRequest) ProtoMessage() {}

func (x *PasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type PasswordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 PasswordRequest_builder) Build() *PasswordRequest {
	m0 := &PasswordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type PasswordResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordResponse) Reset() {
	*x = PasswordResponse{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordResponse) ProtoMessage() {}

func (x *PasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type PasswordResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 PasswordResponse_builder) Build() *PasswordResponse {
	m0 := &PasswordResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type CardsRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardsRequest) Reset() {
	*x = CardsRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardsRequest) ProtoMessage() {}

func (x *CardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type CardsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 CardsRequest_builder) Build() *CardsRequest {
	m0 := &CardsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type CardData struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CardNumber string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3"`
	xxx_hidden_Active     bool                   `protobuf:"varint,2,opt,name=active,proto3"`
	xxx_hidden_ExpiryDate *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expiry_date,json=expiryDate,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CardData) Reset() {
	*x = CardData{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardData) ProtoMessage() {}

func (x *CardData) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CardData) GetCardNumber() string {
	if x != nil {
		return x.xxx_hidden_CardNumber
	}
	return ""
}

func (x *CardData) GetActive() bool {
	if x != nil {
		return x.xxx_hidden_Active
	}
	return false
}

func (x *CardData) GetExpiryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ExpiryDate
	}
	return nil
}

func (x *CardData) SetCardNumber(v string) {
	x.xxx_hidden_CardNumber = v
}

func (x *CardData) SetActive(v bool) {
	x.xxx_hidden_Active = v
}

func (x *CardData) SetExpiryDate(v *timestamppb.Timestamp) {
	x.xxx_hidden_ExpiryDate = v
}

func (x *CardData) HasExpiryDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiryDate != nil
}

func (x *CardData) ClearExpiryDate() {
	x.xxx_hidden_ExpiryDate = nil
}

type CardData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CardNumber string
	Active     bool
	ExpiryDate *timestamppb.Timestamp
}

func (b0 CardData_builder) Build() *CardData {
	m0 := &CardData{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_CardNumber = b.CardNumber
	x.xxx_hidden_Active = b.Active
	x.xxx_hidden_ExpiryDate = b.ExpiryDate
	return m0
}

type CardsResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cards *[]*CardData           `protobuf:"bytes,1,rep,name=cards,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CardsResponse) Reset() {
	*x = CardsResponse{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardsResponse) ProtoMessage() {}

func (x *CardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CardsResponse) GetCards() []*CardData {
	if x != nil {
		if x.xxx_hidden_Cards != nil {
			return *x.xxx_hidden_Cards
		}
	}
	return nil
}

func (x *CardsResponse) SetCards(v []*CardData) {
	x.xxx_hidden_Cards = &v
}

type CardsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Cards []*CardData
}

func (b0 CardsResponse_builder) Build() *CardsResponse {
	m0 := &CardsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Cards = &b.Cards
	return m0
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\bgokeeper\x1a\x1fgoogle/protobuf/timestamp.proto\"\x10\n" +
	"\x0eProfileRequest\"b\n" +
	"\x0fProfileResponse\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"\x11\n" +
	"\x0fPasswordRequest\"\x12\n" +
	"\x10PasswordResponse\"\x0e\n" +
	"\fCardsRequest\"\x80\x01\n" +
	"\bCardData\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12;\n" +
	"\vexpiry_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiryDate\"9\n" +
	"\rCardsResponse\x12(\n" +
	"\x05cards\x18\x01 \x03(\v2\x12.gokeeper.CardDataR\x05cardsB*Z(github.com/Albert-Ti/go-keeper/pkg/protob\x06proto3"

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_user_proto_goTypes = []any{
	(*ProfileRequest)(nil),        // 0: gokeeper.ProfileRequest
	(*ProfileResponse)(nil),       // 1: gokeeper.ProfileResponse
	(*PasswordRequest)(nil),       // 2: gokeeper.PasswordRequest
	(*PasswordResponse)(nil),      // 3: gokeeper.PasswordResponse
	(*CardsRequest)(nil),          // 4: gokeeper.CardsRequest
	(*CardData)(nil),              // 5: gokeeper.CardData
	(*CardsResponse)(nil),         // 6: gokeeper.CardsResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_user_proto_depIdxs = []int32{
	7, // 0: gokeeper.CardData.expiry_date:type_name -> google.protobuf.Timestamp
	5, // 1: gokeeper.CardsResponse.cards:type_name -> gokeeper.CardData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
